global:
  scrape_interval: 15s # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['immogestion_node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['immogestion_cadvisor:8080']

  - job_name: 'api-dev'
    static_configs:
      - targets: ['api_dev:8080']