root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
delay = 1000
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", ".git", "node_modules"]

[misc]
clean_on_exit = true